// <auto-generated />
namespace ClassLibrary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _whatever_the_fuck_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_whatever_the_fuck_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201710311936011__whatever_the_fuck_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
